# User Settings | Edit there as per required

title: jenny plunkett
url: "http://jennyplunkett.me"
baseurl: ""

# This will show up at the top of index page
site_heading: >
    jenny <span class="faded">plunkett</span>

email: jplunkett@utexas.edu
author: Jenny Plunkett
# This description will show up in google search results
# (for index page) etc.
description: >
    Jenny Plunkett's Portfolio

# This will what will show against &copy; in the footer
copyright: jenny plunkett 2020
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: true        # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    Applications Engineer @ Arm

permalink: /:title

# Comments are powered by disqus
comments: false

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Applications Engineer @ Arm

about_footer: true

twitter_username: jennymplunkett
github_username: yennster
facebook_id: jennymplunkett

favicon: true
favicon_location: "/favicon.ico"

profile_picture: "/images/me.png"
paginate: 6
paginate_path: "/page/:num"
tracking_id: UA-77553527-4 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/me.png" # This will show in facebook thumbnails
twitter_image: "images/me.png" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
